### ISSUE TITLE
How to flash dots? 

### ISSUE THREAD

**Issue by IvSatel** [AKJ7/TM1637#14]
I get the temperature, the separator is a colon. how do they blink?

**Comment by IvSatel** [comment]
`#include <TM1637.h>
#include <OneWire.h>
#include <DallasTemperature.h>

#define ONE_WIRE_BUS 8
#define CLK 2
#define DIO 3

TM1637 tm1637(2, 3);
OneWire oneWire(ONE_WIRE_BUS);
DallasTemperature sensors(&oneWire);

void setup(void){
  
  Serial.begin(9600);
  sensors.begin();
  tm1637.init();
  tm1637.setBrightness(1);
}

void loop(void){

  sensors.requestTemperatures();
  String a = String(sensors.getTempCByIndex(0));
    
  tm1637.display(a);
  delay(1000);
  tm1637.clearScreen();
  a.replace(".", "");
  tm1637.display(a);
}`

**Comment by AKJ7** [comment]
Some of those displays supports turning the dots on, some can only turn the colon on. It seems that yours can only turn the colon on.
