### ISSUE TITLE
The number 29.65 displays as 29:65 

### ISSUE THREAD

**Issue by IvSatel** [AKJ7/TM1637#15]

**Comment by AKJ7** [comment]
This just means that the version of the TM1637 that you bought doesn't support the '.'. 

Some context: 
The TM1637 chip allows to switch the state of 8 Segments. These are the 7 usual ones and the last one is either used for the dots '.' after the digits or the colon ':'.

**Comment by IvSatel** [comment]
![photo_2022-01-30_09-43-43](https://user-images.githubusercontent.com/11197418/151689688-9c9ca688-32bc-4651-a76d-410b161aa4fd.jpg)
