### ISSUE TITLE
&animator_ and clearScreen() with cache_

### ISSUE THREAD

**Issue by martind69** [AKJ7/TM1637#18]
If i tried to toggle between display() and clear() in my code. i found an issue with the return object &animator_
it returns null or empty after clear()

    display(const T value, bool overflow = true, bool pad = false, uint8_t offset = 0)
    {
        String temp = stringer<T>(value);
	//bugfix: no cache
        //if (temp == cache_)
        //    return &animator_;
        //cache_ = temp;

    void clear()
    {
        buffer_ = "";
        for (size_t counter{}; counter < totalDigits_; ++counter)
            buffer_.concat(static_cast<char>(0x00u));
        refresh();
    }

**Comment by AKJ7** [comment]
Can you show me your code?

**Comment by martind69** [comment]
void tmDisplay()
{
    switch(pbGroup) {
      // Zugangscode = 2739
      // Richtige Antwort1, Taste A & H = 0b01111110 = 0x7E
      case 0x7E:  tm.display("   2");
                  if(debug_mode) { Serial.println("Loop Case 0x7E"); }
                  break;
      .....
      // Alle anderen Fälle
      default:    tm.clearScreen();
                  break;
    }
}
void loop()
{
    getBits();
    ledSequence();
    tmDisplay();
}

**Comment by AKJ7** [comment]
Yo, thanks for the bug report. I will look into it.

**Comment by martind69** [comment]
tm.clearScreen() is only an alias for that clear function.

**Comment by AKJ7** [comment]
Ah, I see what you mean! Fixing it in the up-coming release. Thanks.

**Comment by AKJ7** [comment]
Fixed in Release #20
