### ISSUE TITLE
error compiling example

### ISSUE THREAD

**Issue by rozrabiak** [AKJ7/TM1637#22]
Hi, on Wemos D1 mini pro (esp8266) I have this error when compile basic example from library:
Library ver. 2.2.0
Platformio.

``
In file included from src\main.cpp:19:
.pio\libdeps\d1_mini_pro\TM1637 Driver\src/TM1637.h: In member function 'Animator* TM1637::offMode() const':
.pio\libdeps\d1_mini_pro\TM1637 Driver\src/TM1637.h:239:16: error: invalid conversion from 'const Animator*' to 'Animator*' [-fpermissive]
  239 |         return &animator_;
      |                ^~~~~~~~~~
      |                |
      |                const Animator*
.pio\libdeps\d1_mini_pro\TM1637 Driver\src/TM1637.h: In member function 'Animator* TM1637::onMode() const':
.pio\libdeps\d1_mini_pro\TM1637 Driver\src/TM1637.h:248:16: error: invalid conversion from 'const Animator*' to 'Animator*' [-fpermissive]
  248 |         return &animator_;
      |                ^~~~~~~~~~
      |                |
      |                const Animator*
``

**Comment by AKJ7** [comment]
Fixed in the latest patch #23. Shoud'nt work during Silvester my man!
