### ISSUE TITLE
Turning off segments

### ISSUE THREAD

**Issue by wip369** [AKJ7/TM1637#4]
Hi, is there an option to turn off the segment of display when not used? For example, if I use encoder and have values from 0-100, is there an option to have blank segment when not used. Instead of having 0001 -> _ _ _ 1 (where _ is totally blank). Nevertheless it's great simple module, but I'm missing this function. Thanks

**Comment by AKJ7** [comment]
Hello, thanks for the issue. This is supposed to be one of the features of the updated version, that i am currently working on (since forever, because i am lazy, but i will resume working on this soon). I will add the feature and hopefully be done by next week.

**Comment by wip369** [comment]
Hi, any new news about update maybe? There's another thing, I've updated to Arduino Nano Every today and your Library is not accepted. Any plans to update that to or it's not in your plan? Thanks

**Comment by AKJ7** [comment]
I have added the possibility to set offsets. 
So for example, you can allow the display to display only on the first 2 digits.
