### ISSUE TITLE
Error compiling the provided example script

### ISSUE THREAD

**Issue by juergen-venne** [AKJ7/TM1637#6]
I get this error compiling the default script:
What do I have to do to get rid of that message?
```
Users/jv/Documents/Arduino/libraries/TM1637_Driver/src/TM1637.cpp: In member function 'const Animator& TM1637::refresh() const':
/Users/jv/Documents/Arduino/libraries/TM1637_Driver/src/TM1637.cpp:53:103: error: call of overloaded 'sendToDisplay(uint8_t* const&, const uint8_t&)' is ambiguous
     sendToDisplay<DataCommand_e::AUTOMATIC_ADDRESS_ADDING, AddressCommand_e::C0H>(buffer_, bufferSize_);
                                                                                                       ^
/Users/jv/Documents/Arduino/libraries/TM1637_Driver/src/TM1637.cpp:53:103: note: candidates are:
In file included from /Users/jv/Documents/Arduino/libraries/TM1637_Driver/src/TM1637.cpp:1:0:
/Users/jv/Documents/Arduino/libraries/TM1637_Driver/src/TM1637.h:173:10: note: void TM1637::sendToDisplay(uint8_t*, uint8_t) const [with TM1637::DataCommand_e dataCommand = (TM1637::DataCommand_e)64u; TM1637::AddressCommand_e addressCommand = (TM1637::AddressCommand_e)192u; uint8_t = unsigned char]
     void sendToDisplay(uint8_t* values, uint8_t size) const noexcept
          ^
/Users/jv/Documents/Arduino/libraries/TM1637_Driver/src/TM1637.h:192:10: note: void TM1637::sendToDisplay(Ts ...) const [with TM1637::DataCommand_e dataCommand = (TM1637::DataCommand_e)64u; TM1637::AddressCommand_e addressCommand = (TM1637::AddressCommand_e)192u; Ts = {unsigned char*, unsigned char}]
     void sendToDisplay(Ts ... values) const noexcept
          ^
exit status 1
Fehler beim Kompilieren für das Board NodeMCU 1.0 (ESP-12E Module).
```

**Comment by jcmadrioso** [comment]
I'm obtaining that error, too. Since your questiong is from Sep 7, and nobody has answered, I guess this project is abandoned. Desinstalling this library right now.

**Comment by AKJ7** [comment]
Oops forgot. I will look into it. Thanks for the comment.

**Comment by AKJ7** [comment]
@jcmadrioso For which platform are you compiling it?

**Comment by jcmadrioso** [comment]
ESP8266

**Comment by AKJ7** [comment]
Solved. However the display doesn't work with 3.3V board like the ESP32 and ESP8266. It expects 5V at the DIO and CLK pins. Sending 3.3 simply doesn't turn the pins on. The solution is to interface the 3.3V to 5V.

**Comment by jcmadrioso** [comment]
Thank you.
But, acording to TM1637 datasheet, the chip works with 3.3V - 5V. In fact, I have used it with ESP8266, ESP32 and RaspberryPi, all of them interfacing at 3.3V, and it works.
I don't know why you say that it needs 5V (see the datasheet).
Best regards.

**Comment by AKJ7** [comment]
What? I tested it on my ESP32 and it wasn't working. Can you update the library and test it?

**Comment by jcmadrioso** [comment]
I can confirm that your library is compiling and working now. I have tested clock.ino example with ESP8266 and it works perfectly, interfacing at 3.3V.
I will try with ESP32.

**Comment by jcmadrioso** [comment]
Yes, working too with ESP32 (ESP-WROOM-32)
Maybe you have an issue with some capacitors in the tm1637 board. Try with a longer bitdelay.

**Comment by AKJ7** [comment]
Ok. Thanks.
